{
  "vi_VN": {
    "version": "Phiên bản",
    "loading_message": "Đang tải dữ liệu!\nVui lòng chờ tý ạ!",
    "schedule": "Lịch Thi Đấu",
    "live": "Đang Diễn Ra"
  },
  "en_US": {
      "version": "Version",
      "loading_message": "Loading!\nPlease wait a moment!",
      "schedule": "Schedule",
      "schedule_empty": "Have no match to show!",
      "live": "Live Matches",
      "live_empty": "No match is being played right now.",
      "favorite": "Favorite Matches",
      "competitions": "Competitions",
      "competitions_empty": "Have no competition to show!",
      "favorite_empty": "You haven't selected any match yet!",
      "schedule_all_matches": "ALL MATCHES",
      "error_message_retry":
          "Have an error!\nClick the logo to retry. Thank you!",
      "dark_mode": "Dark mode",
      "timezone": "Time zone",
      "rate_app": "Rate this App",
      "upgrade": "Upgrade to Pro version",
      "summary": "Summary",
      "statistics": "Statistics",
      "lineup": "Lineups",
      "h2h": "H2H",
      "standing": "Standing",
      "results": "Results",
      "fixtures": "Fixtures",
      "possession": "Ball Possession (%)",
      "shots_on_target": "Shots On Target",
      "shots_off_target": "Shots Off Target",
      "shots_blocked": "Shots Blocked",
      "corner_kicks": "Corner Kicks",
      "offsides": "Offsides",
      "fouls": "Fouls",
      "yellow_cards": "Yellow Cards",
      "red_cards": "Red Cards",
      "throw_ins": "Throw-ins",
      "crosses": "Crosses",
      "goalkeeper_saves": "Goalkeeper Saves",
      "goal_kicks": "Goal Kicks",
      "treatments": "Treatments",
      "counter_attacks": "Counter Attacks",
      "first_half": "First Half",
      "second_half": "Second Half",
      "extra_time": "Extra Time",
      "penalties": "Penalties",
      "starting_lineups": "Starting Lineups",
      "substitutes": "Substitutes",
      "coaches": "Coaches",
      "last_matches": "Last Matches: ",
      "h2h_matches": "Head-to-Head Matches",
      "h2h_empty": "No match found!",
      "error_title": "Error!",
      "error_message": "An error occurred, please try again later.",
      "search": "Search by team...",
      "search_empty": "No result found."
  }
}
